services:
  backend:
    build: ./backend-git-masters
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: ["sh", "./entrypoint.sh"]
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: postgresql://postgres:GrupoASD*@db:5432/git_master

    # opcional si quieres usar el .env
    env_file:
      - .env

  frontend:
    build: ./frontend-git-masters
    container_name: react_app
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:8000

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - backend
    command: http backend:8000
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    ports:
      - "4040:4040"

volumes:
  postgres_data: