services:

  backend:
    image: brayanib14/backend:1.0
    container_name: fastapi_app

    ports:
      - "8000:8000"

    depends_on:
      - db

    restart: unless-stopped

    env_file:
      - .env

    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"


  frontend:
    image: brayanib14/frontend:1.0
    container_name: react_app

    ports:
      - "5173:5173"

    depends_on:
      - backend

    restart: unless-stopped

    environment:
      VITE_API_URL: http://localhost:8000

    command: npm run dev -- --host 0.0.0.0


  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare_tunnel

    depends_on:
      - backend

    env_file:
      - .env

    restart: unless-stopped

    command: tunnel run


  db:
    image: postgres:15
    container_name: postgres_db

    restart: always

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: